services:
  - type: web
    name: learning-log
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn learning_log.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learninglogdb  # Nome exato do seu banco no Render
          property: connectionString
      - key: DEBUG
        value: "False"
